### ISSUE TITLE
iOS safari设置平滑滚动后，fixed定位错误

### ISSUE THREAD

**Issue by axetroy** [axetroy/stackoverflow#16]
Safari 设置平滑滚动
```css
body {
  -webkit-overflow-scrolling:touch;
}
```

如果页面有``position: fixed``的元素

则需要设置transform

```css
.element {
  position: fixed;
  transform: translateZ(0);
  -webkit-transform: translateZ(0);
}
```
