### ISSUE TITLE
Docker部署postgres无法挂载卷，让数据持久化

### ISSUE THREAD

**Issue by axetroy** [axetroy/stackoverflow#8]
系统MacOS
我发现以相对路径去挂载卷是失败，直接指定绝对路径

```yml
  pg:
    image: postgres:9.6
    restart: always
    volumes:
      - "/Users/axetroy/gpm/github.com/axetroy/i18n/docker/volumes/pg:/var/lib/postgresql/data:rw"
    ports:
      - 6432:5432 # 本地端口:容器端口
```
